/tf_static:
  durability: transient_local
  history: keep_last
  depth: 1
  reliability: reliable
/tf:
  durability: volatile
  history: keep_last
  depth: 100
  reliability: reliable
/sensors/lidar/points:
  durability: volatile
  history: keep_last
  depth: 10
  reliability: best_effort
/sensors/imu:
  durability: volatile
  history: keep_last
  depth: 100
  reliability: best_effort
