<?xml version="1.0"?>
<package format="3">
  <name>uf_visual_frontend</name>
  <version>0.1.0</version>
  <description>Exact-synchronized RGB-D sparse feature frontend for Ultra-Fusion.</description>
  <maintainer email="2025111580@stu.hit.edu.cn">Yicheng-Zhu</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>uf_interfaces</exec_depend>
  <exec_depend>uf_backend_fusion</exec_depend>
  <exec_depend>uf_shared_mapping</exec_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
