<?xml version="1.0"?>
<package format="3">
  <name>optical_flow_microlink_cpp</name>
  <version>0.1.0</version>
  <description>Low-overhead Gazebo optical-flow and MicoLink-compatible sensor bridge.</description>
  <maintainer email="zyc@example.com">zyc</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>mavros_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>gz-msgs10</depend>
  <depend>gz-transport13</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
