<?xml version="1.0"?>
<package format="3">
  <name>multi_slam_worlds</name>
  <version>0.1.0</version>
  <description>Gazebo Sim / Harmonic world set for multi-source UAV SLAM and navigation tests.</description>
  <maintainer email="zyc@example.com">zyc</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
