#!/usr/bin/env bash
set -Eeo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

# Dedicated observable calibration maneuver. It intentionally uses FCU-local
# setpoints only during the excitation warm-up, then switches to the unified
# backend for the post-calibration hold and ExternalNav validation.
export VALIDATION_ROUTE=s_curve
export VALIDATION_CALIBRATION_ONLY=true
export VALIDATION_ENABLE_EXTERNALNAV_EKF3=1
export VALIDATION_ENABLE_VISION=1
export VALIDATION_REQUIRE_VISUAL_FACTORS=1
export VALIDATION_RECORD_REPLAY_BAG=true
export VALIDATION_REQUIRE_TIME_CALIBRATION_LOCK=true
export VALIDATION_REQUIRE_VISUAL_TIME_CALIBRATION_LOCK=true
export VISUAL_TIME_CALIBRATION_APPLY_LOCKED=${VISUAL_TIME_CALIBRATION_APPLY_LOCKED:-false}
export VALIDATION_REQUIRE_TIME_CALIBRATION_APPLIED=${VALIDATION_REQUIRE_TIME_CALIBRATION_APPLIED:-false}
export VALIDATION_START_FASTLIO_CLOUD_MAPPER=0
export VALIDATION_START_FASTLIO_OCCUPANCY_GRID=0
export VALIDATION_CALIBRATION_YAW_SWEEP_DEG=${VALIDATION_CALIBRATION_YAW_SWEEP_DEG:-30.0}
export VALIDATION_CALIBRATION_YAW_CYCLES=${VALIDATION_CALIBRATION_YAW_CYCLES:-4.0}
export VALIDATION_CALIBRATION_MOTION_RADIUS_M=${VALIDATION_CALIBRATION_MOTION_RADIUS_M:-1.0}
export VALIDATION_CALIBRATION_MOTION_SPEED_MPS=${VALIDATION_CALIBRATION_MOTION_SPEED_MPS:-0.60}
export TAKEOFF_ALT=${TAKEOFF_ALT:-4.0}
export MINIMUM_CLEARANCE_ALT=${MINIMUM_CLEARANCE_ALT:-3.5}
export METRICS_DURATION=${METRICS_DURATION:-105}
export DRIFT_DURATION=${DRIFT_DURATION:-95}

exec bash "$REPO_ROOT/tools/run_unified_rectangle_validation.sh"
