#!/usr/bin/env bash
set -Eeo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

# Stable milestone policy: one short rectangle, all five factors enabled, and
# the single unified state consumed by ArduPilot EKF3. Online time calibration
# remains observable in diagnostics but cannot modify production timestamps.
export VALIDATION_ROUTE=${VALIDATION_ROUTE:-rectangle}
export VALIDATION_ENABLE_EXTERNALNAV_EKF3=${VALIDATION_ENABLE_EXTERNALNAV_EKF3:-1}
export VALIDATION_ENABLE_VISION=${VALIDATION_ENABLE_VISION:-1}
export VALIDATION_REQUIRE_VISUAL_FACTORS=${VALIDATION_REQUIRE_VISUAL_FACTORS:-1}
export VALIDATION_RECORD_REPLAY_BAG=${VALIDATION_RECORD_REPLAY_BAG:-true}
export VALIDATION_REQUIRE_TIME_CALIBRATION_LOCK=${VALIDATION_REQUIRE_TIME_CALIBRATION_LOCK:-false}
export VALIDATION_REQUIRE_TIME_CALIBRATION_APPLIED=${VALIDATION_REQUIRE_TIME_CALIBRATION_APPLIED:-false}
export VALIDATION_START_FASTLIO_CLOUD_MAPPER=${VALIDATION_START_FASTLIO_CLOUD_MAPPER:-0}
export VALIDATION_START_FASTLIO_OCCUPANCY_GRID=${VALIDATION_START_FASTLIO_OCCUPANCY_GRID:-0}
export METRICS_DURATION=${METRICS_DURATION:-135}
export DRIFT_DURATION=${DRIFT_DURATION:-125}

exec bash "$REPO_ROOT/tools/run_unified_rectangle_validation.sh"
