#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

# Experimental structural scene only. The frozen low-indoor world remains the
# default for all existing validation entry points.
export VALIDATION_WORLD_NAME=${VALIDATION_WORLD_NAME:-low_indoor_apm_rgbd_mid360_window}
export VALIDATION_ROUTE=${VALIDATION_ROUTE:-s_curve}
export VALIDATION_TAKEOFF_ALT=${VALIDATION_TAKEOFF_ALT:-2.2}
export VALIDATION_ENABLE_VISION=${VALIDATION_ENABLE_VISION:-1}
export VALIDATION_VISUAL_FACTOR_MODE=${VALIDATION_VISUAL_FACTOR_MODE:-rgbd_direct}
export VALIDATION_RGBD_MAXIMUM_DEPTH_M=${VALIDATION_RGBD_MAXIMUM_DEPTH_M:-10.0}
export VALIDATION_AXIS_INFORMATION_HANDOFF_ENABLED=${VALIDATION_AXIS_INFORMATION_HANDOFF_ENABLED:-true}
export VALIDATION_RANGE_FACET_ENABLED=${VALIDATION_RANGE_FACET_ENABLED:-false}
export VALIDATION_BAROMETER_FALLBACK_ENABLED=${VALIDATION_BAROMETER_FALLBACK_ENABLED:-false}
export VALIDATION_ENABLE_EXTERNALNAV_EKF3=${VALIDATION_ENABLE_EXTERNALNAV_EKF3:-1}
export VALIDATION_REQUIRE_VISUAL_FACTORS=${VALIDATION_REQUIRE_VISUAL_FACTORS:-1}
export VALIDATION_ROUTE_FEEDBACK_SOURCE=${VALIDATION_ROUTE_FEEDBACK_SOURCE:-unified_backend}
export VALIDATION_START_FASTLIO_CLOUD_MAPPER=${VALIDATION_START_FASTLIO_CLOUD_MAPPER:-0}
export VALIDATION_START_FASTLIO_OCCUPANCY_GRID=${VALIDATION_START_FASTLIO_OCCUPANCY_GRID:-0}

# Keep the passive baseline as the default for the first scene comparison.
# Active EGO-style motion can be enabled explicitly in a later experiment.
export VALIDATION_RELOCALIZATION_MOTION_PROFILE=${VALIDATION_RELOCALIZATION_MOTION_PROFILE:-hold}
export VALIDATION_RELOCALIZATION_VELOCITY_POLICY=${VALIDATION_RELOCALIZATION_VELOCITY_POLICY:-stationary_zero}
export VALIDATION_RELOCALIZATION_BIAS_POLICY=${VALIDATION_RELOCALIZATION_BIAS_POLICY:-preserve}
export LOG_DIR=${LOG_DIR:-$REPO_ROOT/logs/window_opening_relocalization_$(date +%Y%m%d_%H%M%S)}

printf 'Experimental world: %s\n' "$VALIDATION_WORLD_NAME"
printf 'Relocalization motion profile: %s\n' "$VALIDATION_RELOCALIZATION_MOTION_PROFILE"
exec bash "$REPO_ROOT/tools/run_unified_rectangle_validation.sh" "$@"
