<?xml version="1.0"?>
<package format="3">
  <name>uf_relocalization</name>
  <version>0.1.0</version>
  <description>Offline registration and relocalization verification for Ultra-Fusion reproduction.</description>
  <maintainer email="zyc@example.com">zyc</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>libpcl-all-dev</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
